'use client';
import { useEffect, useState } from 'react';

interface Kpi { label: string; value: number; deltaPct: number; money: boolean; isPct?: boolean }
interface Decision { priority: number; category: string; title: string; expectedResult: string; confidence: number; recommendation: string }
interface Report {
  period: string; range: { from: string; to: string }; generatedAt: string;
  kpis: Kpi[]; decisions: Decision[];
}

const PERIODS = ['weekly', 'monthly', 'quarterly'] as const;
const money = (n: number) => {
  const a = Math.abs(Math.round(n));
  const s = a >= 1e6 ? `$${(a / 1e6).toFixed(2)}M` : a >= 1e3 ? `$${(a / 1e3).toFixed(1)}K` : `$${a}`;
  return n < 0 ? `-${s}` : s;
};
const kval = (k: Kpi) => (k.isPct ? `${k.value}%` : k.money ? money(k.value) : k.value.toLocaleString());

export default function ReportGenerator() {
  const [period, setPeriod] = useState<typeof PERIODS[number]>('monthly');
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    setLoading(true);
    fetch(`/api/intelligence/report?period=${period}`).then((r) => r.json()).then((d) => { setReport(d); setLoading(false); }).catch(() => setLoading(false));
  }, [period]);

  async function downloadPdf() {
    if (!report) return;
    setDownloading(true);
    try {
      const { jsPDF } = await import('jspdf');
      const autoTable = (await import('jspdf-autotable')).default;
      const doc = new jsPDF();
      const title = `RetailNexa AI — ${period[0].toUpperCase() + period.slice(1)} Executive Report`;

      doc.setFontSize(18); doc.setTextColor(30, 27, 75); doc.text(title, 14, 20);
      doc.setFontSize(10); doc.setTextColor(120);
      doc.text(`Period: ${report.range.from} to ${report.range.to}   ·   Generated ${new Date(report.generatedAt).toLocaleDateString()}`, 14, 27);

      doc.setFontSize(13); doc.setTextColor(30, 27, 75); doc.text('Key Performance Indicators', 14, 38);
      autoTable(doc, {
        startY: 42,
        head: [['Metric', 'Value', 'vs prior period']],
        body: report.kpis.map((k) => [k.label, kval(k), k.deltaPct ? `${k.deltaPct >= 0 ? '+' : ''}${k.deltaPct}%` : '—']),
        theme: 'striped', headStyles: { fillColor: [99, 102, 241] }, styles: { fontSize: 10 },
      });

      // @ts-expect-error autotable augments doc with lastAutoTable
      let y = (doc.lastAutoTable?.finalY ?? 60) + 12;
      doc.setFontSize(13); doc.setTextColor(30, 27, 75); doc.text('Recommended Decisions', 14, y);
      autoTable(doc, {
        startY: y + 4,
        head: [['#', 'Category', 'Decision', 'Expected result', 'Conf.']],
        body: report.decisions.map((d) => [d.priority, d.category, d.title, d.expectedResult, `${Math.round(d.confidence * 100)}%`]),
        theme: 'striped', headStyles: { fillColor: [99, 102, 241] }, styles: { fontSize: 9, cellWidth: 'wrap' },
        columnStyles: { 2: { cellWidth: 60 }, 3: { cellWidth: 50 } },
      });

      // @ts-expect-error lastAutoTable
      y = (doc.lastAutoTable?.finalY ?? 120) + 10;
      doc.setFontSize(8); doc.setTextColor(150);
      doc.text('Generated by RetailNexa AI · Open-source decision intelligence · Forecasts use Holt-Winters; CLV/churn via RFM; inventory via service-level safety stock.', 14, y, { maxWidth: 180 });

      doc.save(`RetailNexa-${period}-report.pdf`);
    } finally {
      setDownloading(false);
    }
  }

  if (loading) return <div className="h-64 flex items-center justify-center text-gray-400 text-sm">Building report…</div>;
  if (!report?.kpis) return <div className="h-64 flex items-center justify-center text-gray-400 text-sm">No report data.</div>;

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex rounded border border-gray-300 overflow-hidden">
          {PERIODS.map((p) => (
            <button key={p} onClick={() => setPeriod(p)}
              className={`text-xs px-3 py-1.5 capitalize ${period === p ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-50'}`}>{p}</button>
          ))}
        </div>
        <button onClick={downloadPdf} disabled={downloading}
          className="text-sm px-4 py-2 rounded-lg bg-indigo-600 text-white font-medium hover:bg-indigo-700 disabled:opacity-50">
          {downloading ? 'Generating…' : '⬇ Download PDF'}
        </button>
      </div>

      {/* On-screen preview */}
      <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm space-y-6">
        <div>
          <h2 className="text-lg font-bold text-gray-900 capitalize">{period} Executive Report</h2>
          <p className="text-xs text-gray-500">{report.range.from} → {report.range.to} · generated {new Date(report.generatedAt).toLocaleDateString()}</p>
        </div>

        <div>
          <h3 className="text-sm font-semibold text-gray-800 mb-2">Key Performance Indicators</h3>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {report.kpis.map((k) => (
              <div key={k.label} className="rounded-lg border border-gray-100 bg-gray-50 p-3">
                <div className="text-[11px] text-gray-500">{k.label}</div>
                <div className="text-xl font-bold text-gray-900">{kval(k)}</div>
                {!!k.deltaPct && <div className={`text-xs font-medium ${k.deltaPct >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{k.deltaPct >= 0 ? '+' : ''}{k.deltaPct}% vs prior</div>}
              </div>
            ))}
          </div>
        </div>

        <div>
          <h3 className="text-sm font-semibold text-gray-800 mb-2">Recommended Decisions</h3>
          <ol className="space-y-2">
            {report.decisions.map((d) => (
              <li key={d.priority} className="flex gap-3 text-sm">
                <span className="flex items-center justify-center w-5 h-5 rounded-full bg-gray-900 text-white text-xs font-bold shrink-0">{d.priority}</span>
                <div>
                  <span className="font-medium text-gray-800">{d.title}</span>
                  <span className="text-gray-500"> — {d.expectedResult} ({Math.round(d.confidence * 100)}%)</span>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </div>
  );
}
